# Generated by Django 2.1 on 2018-08-06 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('imdbID', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('plot', models.CharField(max_length=600)),
                ('runtime', models.CharField(max_length=6)),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('writer', models.CharField(max_length=50)),
                ('actors', models.CharField(max_length=200)),
                ('language', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('poster', models.CharField(max_length=200)),
                ('total_seasons', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
        ),
    ]
