# Generated by Django 2.1 on 2018-08-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20180807_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='movie',
            new_name='movie_id',
        ),
    ]
